// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadModel(arg1:string):Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetHotkey():Promise<string>;

export function GetHotkeyStatus():Promise<string>;

export function GetLaunchAtLogin():Promise<boolean>;

export function GetModelStatuses():Promise<Record<string, string>>;

export function GetStatus():Promise<string>;

export function OpenSystemSettings():Promise<void>;

export function Quit():Promise<void>;

export function SaveWindowPosition():Promise<void>;

export function SetAudioService(arg1:main.audioStarter):Promise<void>;

export function SetConfigService(arg1:main.ConfigService):Promise<void>;

export function SetHotkey(arg1:string):Promise<void>;

export function SetHotkeyService(arg1:main.hotkeyStarter):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetLaunchAtLogin(arg1:boolean):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function SetModelService(arg1:main.ModelService):Promise<void>;

export function SetOutputService(arg1:main.outputRunner):Promise<void>;

export function SetWhisperService(arg1:main.whisperRunner):Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleWindow():Promise<void>;
