// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetHotkeyStatus():Promise<string>;

export function GetLaunchAtLogin():Promise<boolean>;

export function GetStatus():Promise<string>;

export function Quit():Promise<void>;

export function SetHotkeyService(arg1:main.hotkeyStarter):Promise<void>;

export function SetLaunchAtLogin(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;
