// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
