// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHotkeyStatus() {
  return window['go']['main']['App']['GetHotkeyStatus']();
}

export function GetLaunchAtLogin() {
  return window['go']['main']['App']['GetLaunchAtLogin']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SetHotkeyService(arg1) {
  return window['go']['main']['App']['SetHotkeyService'](arg1);
}

export function SetLaunchAtLogin(arg1) {
  return window['go']['main']['App']['SetLaunchAtLogin'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
